name: Build and Package

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

#      - name: Install dependencies
#        run: composer install --no-interaction --prefer-dist --optimize-autoloader

#      - name: Run tests
#        run: composer test || true

      - name: Build and package
        run: |
          mkdir build
          cp -r $GITHUB_WORKSPACE/* build/
          cd build
          zip -r ../deploy-package.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy-package.zip