name: Do Some Deployment

on:
  workflow_run:
    workflows: ["Build and Package"]
    types:
      - completed

jobs:
  deploy:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 下載 artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: 部署步驟
        run: |
          echo "開始部署"