name: Build and Package

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-package:
    environment: dev
    outputs:
      ARTIFACT_NAME: $ARTIFACT_NAME
      JOB_RUN_ID: $GITHUB_RUN_ID

    runs-on: self-hosted

    steps:
      - name: 設定動態變數
        run: echo "ARTIFACT_NAME=$ENV_NAME-package" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: source-code

      - name: show github workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo pwd
          echo ls -al
          echo ls -al $GITHUB_WORKSPACE
          echo ls -al ../

      - name: Build and package
        run: |
          mkdir build
          cp -r source-code/* build/
          cd build
          zip -r ../deploy-package.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: $ARTIFACT_NAME
          path: build/
