name: Do Some Deployment

on:
  workflow_run:
    workflows: ["Build and Package"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 取得 BUILD_JOB_ID
        run: echo "BUILD_JOB_ID=${{ github.event.inputs.job_run_id }}" >> $GITHUB_ENV

      - name: 下載 artifact
        uses: actions/download-artifact@v4
        with:
          artifact-ids: 16004412877

      - name: 部署步驟
        run: |
          echo "開始部署"