name: manual-download-artifact.yaml
on:
  workflow_dispatch:
    inputs:
      ARTIFACT_NAME:
        description: 'Artifact name to download'
        required: true
        default: 'Artifact Name'
      JOB_RUN_ID:
        description: 'Run ID'
        required: true
        default: 'Run ID'

jobs:
    download-artifact:
        runs-on: ubuntu-latest
        steps:
          - name: 下載特定 artifact
            uses: actions/download-artifact@v4
            with:
              name: ${{ github.event.inputs.ARTIFACT_NAME }}
              github-token: ${{ secrets.GH_TOKEN }} # token with actions:read permissions on target repo
              repository: ${{ github.repository }}
              run-id: ${{ github.event.inputs.JOB_RUN_ID }}

          - name: 列出下載的檔案
            run: |
              echo "Downloaded files:"
              ls -R
              echo "Download complete."

