name: manual-download-artifact.yaml
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID'
        required: true
        default: 'Run ID'

jobs:
    download-artifact:
        runs-on: ubuntu-latest
        steps:
          - name: 下載特定 artifact
            uses: actions/download-artifact@v4
            with:
              name: dev-build-and-package.yaml
              github-token: ${{ secrets.GH_TOKEN }} # token with actions:read permissions on target repo
              repository: jrg-vincechang/test-project-01
              run-id: ${{ github.event.inputs.run_id }}

