name: manual-download-artifact.yaml
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to download artifact from'
        required: true
        default: 'Repository Name'
      artifact_name:
        description: 'Artifact name to download'
        required: true
        default: 'Artifact Name'
      run_id:
        description: 'Run ID'
        required: true
        default: 'Run ID'

jobs:
    download-artifact:
        runs-on: ubuntu-latest
        steps:
          - name: 下載特定 artifact
            uses: actions/download-artifact@v4
            with:
              name: ${{ github.event.inputs.artifact_name }}
              github-token: ${{ secrets.GH_TOKEN }} # token with actions:read permissions on target repo
              repository: ${{ github.event.inputs.repository }}
              run-id: ${{ github.event.inputs.run_id }}

